M48
; DRILL file {KiCad (6.0.7-1)-1} date Tuesday, August 16, 2022 at 07:52:37 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-16T19:52:37+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X4.0Y-4.0
X4.0Y-55.0
X92.75Y-4.0
X92.75Y-55.0
T0
M30
